<?php
/**
 * This file is part of Emotionally.
 *
 * Emotionally is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Emotionally is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Emotionally.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * This file is part of Emotionally.
 *
 * Emotionally is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Emotionally is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Emotionally.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Emotionally\Http\Controllers\ReportFormatters\Presentations;

use Emotionally\Http\Controllers\ReportController;
use Emotionally\Http\Controllers\ReportFormatters\ReportFormatter;
use PhpOffice\PhpPresentation\DocumentLayout;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\Shape\Chart;
use PhpOffice\PhpPresentation\Shape\Chart\Series;
use PhpOffice\PhpPresentation\Shape\Chart\Type\Bar;
use PhpOffice\PhpPresentation\Shape\RichText;
use PhpOffice\PhpPresentation\Slide;
use PhpOffice\PhpPresentation\Slide\Background\Color as BackgroundColor;
use PhpOffice\PhpPresentation\Style\Alignment;
use PhpOffice\PhpPresentation\Style\Color;
use PhpOffice\PhpPresentation\Style\Fill;
use PhpOffice\PhpPresentation\Style\Shadow;

abstract class ReportPresentation extends ReportFormatter
{

    protected const COLOR_PRIMARY = 'FFFF9800';
    protected const COLOR_WHITE = 'FFFFFFFF';

    /**
     * The type of report
     */
    protected const TYPE = 'NO TYPE';

    /**
     * @var PhpPresentation The presentation
     */
    protected $presentation;

    /**
     * @var Slide The title slide.
     */
    protected $title_slide;

    /**
     * @var array<Slide> The presentation slides.
     */
    protected $slides;

    /**
     * ReportPresentation constructor.
     * @param string $title The title of the presentation.
     * @param array|string $report The report to be presented.
     */
    public function __construct(string $title, $report)
    {
        parent::__construct($title, $report);

        $this->slides = array();

        $this->presentation = new PhpPresentation();

        $this->presentation->getDocumentProperties()
            ->setTitle($title)
            ->setCreator(\Auth::user()->name . ' ' . \Auth::user()->surname)
            ->setLastModifiedBy('Emotionally - FSC');

        $this->presentation->getLayout()
            ->setDocumentLayout(DocumentLayout::LAYOUT_SCREEN_16X9);
    }

    /**
     * Create the title slide.
     */
    public function createTitleSlide()
    {
        $this->title_slide = $this->presentation->getActiveSlide();
        $background = (new BackgroundColor())->setColor(new Color(self::COLOR_PRIMARY));
        $this->title_slide->setBackground($background);

        $shape = $this->title_slide->createRichTextShape()
            ->setHeight(300)
            ->setWidth(600)
            ->setOffsetX(180)
            ->setOffsetY(120);

        $shape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $textRun = $shape->createTextRun($this::TYPE);
        $textRun->getFont()
            ->setSize(32)
            ->setCharacterSpacing(16)
            ->setColor(new Color(self::COLOR_WHITE));

        $shape->createBreak();

        $textRun = $shape->createTextRun('“' . $this->title . '”');
        $textRun->getFont()
            ->setBold(true)
            ->setSize(60)
            ->setColor(new Color(self::COLOR_WHITE));

        $shape->createBreak();

        $textRun = $shape->createTextRun('Generated by Emotionally, made with love by FSC');
        $textRun->getFont()
            ->setSize(11)
            ->setColor(new Color('DDFFFFFF'));

        array_push($this->slides, $this->title_slide);
        return $this;
    }

    /**
     * @return Slide Get a reference to the title slide.
     */
    public function getTitleSlide()
    {
        return $this->title_slide;
    }

    /**
     * @inheritDoc
     */
    public function getFileName()
    {
        return $this->getFileBaseName() . '.pptx';
    }

    /**
     * @inheritDoc
     */
    public function getFileAsBinaryOutput()
    {
        $writer = IOFactory::createWriter($this->presentation, 'PowerPoint2007');
        $writer->save('php://output');
    }

    /**
     * Add a slide containing the highest emotion.
     * @return $this
     */
    public function addHighestEmotionSlide()
    {
        $averageEmotion = ReportController::highestEmotion($this->report);
        $new_slide = $this->presentation->createSlide();
        $new_slide->setName('yello');
        array_push($this->slides, $new_slide);

        $title_shape = $new_slide->createRichTextShape()
            ->setWidth(300)
            ->setHeight(60)
            ->setOffsetX(70)
            ->setOffsetY(50)
            ->setAutofit(RichText::AUTOFIT_SHAPE);

        $title = $title_shape->createTextRun('Modal Emotion');
        $title->getFont()
            ->setSize(32)
            ->setColor(new Color(self::COLOR_PRIMARY));

        // Image (emoji)
        $image_offset_x = 355;
        $image_width = 248;
        $shape = $new_slide->createDrawingShape();
        $shape->setName('Modal emotion')
            ->setDescription('Modal emotion: ' . $averageEmotion)
            ->setPath('images/emotions/' . $averageEmotion . '.png')
            ->setResizeProportional(false)
            ->setHeight($image_width)
            ->setWidth($image_width)
            ->setOffsetX($image_offset_x)
            ->setOffsetY(150);
        $shape->getShadow()->setVisible(true)
            ->setDirection(45)
            ->setDistance(10);

        // Image caption
        $desc_shape = $new_slide->createRichTextShape()
            ->setWidth($image_width)
            ->setHeight(30)
            ->setOffsetX($image_offset_x)
            ->setOffsetY(420)
            ->setAutofit(RichText::AUTOFIT_SHAPE);

        $desc_shape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $desc = $desc_shape->createTextRun(strtoupper($averageEmotion));
        $desc->getFont()
            ->setSize(16)
            ->setCharacterSpacing(6)
            ->setColor(new Color('FF777777'));

        return $this;
    }

    /**
     * Add a slide containing a bar chart with the emotion values
     * @warning Due to a bug in the used library this method can't be used to generate
     * a slide, otherwise it will break the whole powerpoint. The error is in the writing of
     * the XML file (as in https://github.com/PHPOffice/PHPPresentation/issues/382)
     * @return $this
     * @throws \Exception
     */
    public function addEmotionsChartSlide()
    {
        $emotions = ReportController::getEmotionValues($this->report);
        $slide = $this->presentation->createSlide();

        $series = new Series('Prova', $emotions);

        $barChart = new Bar();
        $barChart->addSeries($series);

        $shape = new Chart();
        $slide->addShape($shape);
        $shape->setName('PHPPresentation Monthly Downloads')
            ->setResizeProportional(false)
            ->setHeight(550)
            ->setWidth(700)
            ->setOffsetX(120)
            ->setOffsetY(80);

        $oFill = new Fill();
        $oFill->setFillType(Fill::FILL_SOLID)->setStartColor(new Color('FFE06B20'));
        $oShadow = new Shadow();
        $oShadow->setVisible(true)->setDirection(45)->setDistance(10);
        $shape->setShadow($oShadow);
        $shape->setFill($oFill);
        $shape->getBorder()->setLineStyle(Border::LINE_SINGLE);
        $shape->getTitle()->setText('PHPPresentation Monthly Downloads');
        $shape->getTitle()->getFont()->setItalic(true);
        $shape->getTitle()->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        $shape->getPlotArea()->getAxisX()->setTitle('Month');
        $shape->getPlotArea()->getAxisY()->getFont()->getColor()->setRGB('00FF00');
        $shape->getPlotArea()->getAxisY()->setTitle('Downloads');
        $shape->getPlotArea()->setType($barChart);
        $shape->getLegend()->getBorder()->setLineStyle(Border::LINE_SINGLE);
        $shape->getLegend()->getFont()->setItalic(true);

        return $this;
    }
}
